#!/bin/bash

source "$(dirname "$0")/lib/common.sh"

if [[ -z "$@" ]]; then
  err "Usage: $(basename "$0") <files>"
fi

exit_code=2

function format_path() {
  local expanded_path="$(readlink -f $1)"
  # replace $HOME/ with '~/', but only when run interactively
  if [[ $- == *i*-t ]] && [[ "$expanded_path" =~ "$HOME/"* ]]; then
    expanded_path="~/${expanded_path#"$HOME/"}"
  fi
  echo "$expanded_path"
}

while true ; do
  for look_for in "$@" ; do
    found="$(find . -maxdepth 1 -name "$look_for")"
    if [ -n "$found" ]; then
      format_path "$found"
      exit_code=0
    fi
  done
  if [[ "$PWD" == '/' || "$PWD" == "$HOME" ]]; then
    break
  fi
  cd ..
done

exit "$exit_code"
