#!/bin/bash

if [[ -z "$JAVA_HOME" ]]; then
  echo 1>&2 'Please set JAVA_HOME first.'
  exit 1
fi

export CLASSPATH="$JAVA_HOME/lib/tools.jar"
if [[ ! -e "$CLASSPATH" ]]; then
  echo 1>&2 "Couldn't find tools.jar in $CLASSPATH"
  exit 1
fi

cd "$(dirname "$0")"
./javarun .java_sources/JdwpFinder.java "$@"
