#!/bin/bash

if [ "$1" = '-R' ]; then
  recursive=$(( $2 ))
  next_recursive_depth=$(( $2 - 1 ))
  shift
  shift
else
  recursive=0
fi
target_dir="$1"
if [ -z "$target_dir" ]; then
  echo 'no dir specified'
  exit 1
fi

# recursively delete snapshots from children
if [ "$recursive" != 0 ]; then
  first=true
  while read -r subdir; do
    if "$first"; then
      first=false;
      continue;
    fi
    if [[ "$subdir" =~ ^d ]]; then
      subdir=$(basename "$subdir")
      echo "recursively deleting snapshots for $target_dir/$subdir"
      "$0" -R $next_recursive_depth "$target_dir/$subdir"
    fi
  done <<< "$(hdfs dfs -ls "$target_dir" 2> /dev/null)"
fi

first=true
while read -r snapshot; do
  if "$first"; then
    first=false;
    continue;
  fi
  snapshot=$(basename "$snapshot")
  printf 'Deleting snapshot %s... ' "$snapshot"
  OUTPUT=$(hdfs dfs -deleteSnapshot "$target_dir" "$snapshot" 2>&1)
  CODE="$?"
  if [ "0" == "$CODE" ]; then
    echo 'OK'
  else
    echo "ERROR: $CODE"
    echo "$OUTPUT"
  fi
done <<< "$(hdfs dfs -ls "$target_dir/.snapshot" 2> /dev/null)"

