#!/bin/bash

# requres moreutils, for vipe

if ! hdfs &>/dev/null ; then
  echo 1>&2 'hdfs command not found'
  exit 1
fi

if [[ "$#" -eq 0 || "$#" -gt 2 ]]; then
  echo "usage $(basename "$0") <path> [ext]" 1>&2
  echo "" 1>&2
  echo "Opens an editor for interactive pasting, then puts the contents into hdfs at the given path." 1>&2
  echo "If [ext] is provided, <path> is assumed to be a directory, and a file will be created in that directory" 1>&2
  echo "with a random name and the given extension: '$(basename "$0") foodir json'" 1>&2
  echo "If [ext] is not provided, <path> is interpreted exactly." 1>&2
  exit 1
fi
EDITOR=${EDITOR:-vim}
if [[ -z "$EDITOR" ]]; then
  echo 'No EDITOR set' 1>&2
  exit 2
fi

UPLOAD_TO="$1"
if [[ $UPLOAD_TO != "/*" ]]; then
  UPLOAD_TO="/tmp/load/test/$UPLOAD_TO"
fi
if [[ -n "$2" ]]; then
  UPLOAD_TO="$UPLOAD_TO/T$(date +%s)$(uuidgen | grep -o -- '-[^-]\+$' | tr 'A-Z' 'a-z').${2}"
fi

IN_FILE="$(mktemp)"
OUT_FILE="$(mktemp)"
if [[ ! -t 0 ]] ; then
  # running this with stdin piped
  cat > "$IN_FILE"
fi
(hdfs dfs -mkdir -p "$(dirname "$UPLOAD_TO")" &>/dev/null &) # create the dir while the user vipes the file
cat "$IN_FILE" | vipe > "$OUT_FILE"
rm "$IN_FILE"

set -e
printf 'Uploading %s ... ' "$UPLOAD_TO"
hdfs dfs -copyFromLocal "$OUT_FILE" "$UPLOAD_TO"
printf 'done.\n'
rm "$OUT_FILE"
