#!/bin/bash

if [[ $# -lt 1 ]]; then
  echo 1>&2 "Usage: $(basename "$0") <.java file> [args]"
  echo 1>&2 "Compiles the .java file if needed, and then runs the class, passing along the given args."
  exit 1
fi

JAVA_FILE_FULL="$1"
shift
cd "$(dirname "$JAVA_FILE_FULL")"
JAVA_FILE="$(basename "$JAVA_FILE_FULL")"

SOURCE_HASH_FILE="$JAVA_FILE.hash"

SOURCE_HASH="$(md5sum "$JAVA_FILE")"
if [[ "$(cat "$SOURCE_HASH_FILE" 2>/dev/null)" != "$SOURCE_HASH" ]]; then
  set -e
  javac -cp "$CLASSPATH" "$JAVA_FILE"
  set +e
  echo "$SOURCE_HASH" > "$SOURCE_HASH_FILE"
fi

java -cp "$CLASSPATH:." "${JAVA_FILE%.*}" "$@"
