#!/bin/bash

if [[ -z "$1" || -n "$2" ]]; then
  echo 1>&2 "Usage $(basename "$0") <file>"
  echo 1>&2 "Opens the given file with less, and then prompts you if you want to delete it."
  exit 1
fi
FILE_NAME="$1"
set -e
vim -R "$FILE_NAME"
while [[ true ]]; do
  read -p "rm $FILE_NAME? " SHOULD_DELETE
  if [[ "$SHOULD_DELETE" == 'yes' || "$SHOULD_DELETE" == 'y' ]]; then
    rm "$FILE_NAME"
    exit 0
  elif [[ "$SHOULD_DELETE" == 'no' || "$SHOULD_DELETE" == 'n' ]]; then
    exit 0
  else
    echo 'Please enter "yes" or "no".'
  fi
done

