#!/bin/bash

ALL_EXTENSIONS=''
EXTENSIONLESS=""
for FILE_NAME in $(ls -1); do
  FILE_EXTENSION=$(echo "$FILE_NAME" | grep -o '\.[^.]\+')
  if [[ -n "$FILE_EXTENSION" ]]; then
    ALL_EXTENSIONS=$(printf '%s\n%s' "$FILE_EXTENSION" "$ALL_EXTENSIONS")
  else
    EXTENSIONLESS=$(printf '%s\n%s' "$FILE_NAME" "$EXTENSIONLESS")
  fi
done
ALL_EXTENSIONS=$(echo "$ALL_EXTENSIONS" | sort | uniq)

FIRST=''
for FILE_EXTENSION in $ALL_EXTENSIONS; do
  if [[ -z "$FIRST" ]] ; then
    FIRST=true
  else
    echo
  fi
  echo "$FILE_EXTENSION:"
  ls -lhtr *$FILE_EXTENSION
done

if [[ -n "$EXTENSIONLESS" ]]; then
  echo
  echo "no extension:"
  ls -lhtr $EXTENSIONLESS
fi
