#!/usr/bin/python

import sys

line_len_chars = 6
line_count_chars = 6

format_str = '%0' + str(line_len_chars) + 'd %0' + str(line_count_chars) + 'd %s'

for i, line in enumerate(sys.stdin):
    sys.stdout.write(format_str % (len(line) - 1, i, line))  # -1 for newline
