#!/usr/bin/python
import os

def by_extension(paths):
    results = {}
    for path in paths:
        ext = os.path.splitext(path)[1]
        if ext == '':
            ext = '<empty>'
        add_to = results.get(ext)
        if add_to is None:
            add_to = []
            results[ext] = add_to
        add_to.append(path)
    for ps in results.values():
        ps.sort()
    return results

def print_paths_by_ext(paths_by_ext):
    def comparator(a, b):
        # number of elements, biggest first; then extension name
        len_cmp = -cmp(len(paths_by_ext[a]), len(paths_by_ext[b]))
        return len_cmp if len_cmp != 0 else cmp(a, b)
    for ext in sorted(paths_by_ext.keys(), cmp=comparator):
        print '%s:' %ext
        for path in paths_by_ext[ext]:
            print '  %s' % path

if __name__ == '__main__':
    def files_iter():
        for root, dirs, files in os.walk('.'):
            # In-place edit to remove dotfiles/dotdirs. os.walk respects this modification.
            dirs[:] = list(filter(lambda d: not d.startswith('.'), dirs))
            for name in files:
                # print '########## <root:%s>   <dirs:%s>   <name:%s>' % (root, dirs, name)
                yield '%s/%s' % (root, name)
    print_paths_by_ext(by_extension(files_iter()))
