#!/usr/bin/python
import sys

# This comment lets you test the file on itself. You should only see it once.
# This comment lets you test the file on itself. You should only see it once.

seen_lines = set()
for l in sys.stdin:
    if l.isspace(): # always print blank lines
        sys.stdout.write(l)
    if not l in seen_lines:
        sys.stdout.write(l)
        seen_lines.add(l)
# This comment lets you test the file on itself. You should only see it once.
