#!/usr/bin/python

import signal
import socket
import sys

if len(sys.argv) != 2:
    import os
    sys.stderr.write('''Usage: %s <port>

Listens to UDP connections on the given port, and prints them out. This is
basically like the TCP equivalent of "nc -kl 0.0.0.0 <port>".

See http://stackoverflow.com/a/7696956/1076640 for why this is needed.
''' % os.path.basename(sys.argv[0]))
    sys.exit(1)

port = int(sys.argv[1])

# trap sigint so that we don't get an ugly stack trace
signal.signal(signal.SIGINT, lambda sig, frame: sys.exit(1))

# "Adapted" from https://wiki.python.org/moin/UdpCommunication

sock = socket.socket(socket.AF_INET,     # Internet
                     socket.SOCK_DGRAM)  # UDP
sock.bind(('127.0.0.1', port))

while True:
    data = sock.recv(4096)
    print data
