#!/bin/bash
source "$(dirname "$0")/lib/common.sh"

project_root="${1:-$PWD}"

single_upsert_script="$(readlink -f "$(dirname "$0")/py/vscode_to_idea_nodeattach.py")"

find "$project_root" -path '*/.vscode/launch.json'  -not -path '*/node_modules/*' -exec python3 "$single_upsert_script" "$project_root" {} \;
