#!python

import yaml
import json
import sys

if sys.argv[1:]:
    loaders = [lambda: open(path) for path in sys.argv[1:]]
else:
    loaders = [lambda: sys.stdin]

for fp in loaders:
    with fp() as f:
        yobjs = yaml.load_all(f)
        for yobj in yobjs:
            print(json.dumps(yobj, indent=2))
